-- Send a push notification to every other member when a user posts a group
-- message. The existing notifications database webhook forwards
-- these rows to registered FCM devices.

create or replace function public.notify_trip_group_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trip_title text;
  v_sender_name text;
  v_preview text;
begin
  -- Call-history records are rendered as messages but are generated by the
  -- call lifecycle. Incoming calls already have their own phone alert.
  if new.body like '[call_history]|%' or new.body like '[system]%' then
    return new;
  end if;

  select destination
    into v_trip_title
  from public.matchmaking_trips
  where id = new.trip_id;

  select coalesce(nullif(trim(display_name), ''), 'A trip member')
    into v_sender_name
  from public.user_accounts
  where id = new.sender_id;

  v_sender_name := coalesce(v_sender_name, 'A trip member');
  v_trip_title := coalesce(nullif(trim(v_trip_title), ''), 'your trip group');
  v_preview := left(regexp_replace(trim(new.body), E'[\\n\\r\\t]+', ' ', 'g'), 160);

  insert into public.notifications (
    user_id,
    trip_id,
    title,
    body,
    metadata
  )
  select
    recipient.user_id,
    new.trip_id,
    v_sender_name || ' in ' || v_trip_title,
    v_preview,
    jsonb_build_object(
      'type', 'group_message',
      'message_id', new.id,
      'sender_id', new.sender_id
    )
  from (
    select owner_id as user_id
    from public.matchmaking_trips
    where id = new.trip_id
    union
    select user_id
    from public.matchmaking_trip_members
    where trip_id = new.trip_id
  ) recipient
  where recipient.user_id <> new.sender_id;

  return new;
end;
$$;

drop trigger if exists on_trip_group_message_sent on public.trip_messages;
create trigger on_trip_group_message_sent
after insert on public.trip_messages
for each row execute function public.notify_trip_group_message();
